import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
import {ChatAppProvider} from "./context/ChatAppContext"
import { Navbar } from './components'
const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ChatAppProvider>
    <html lang="en">
        <body className={inter.className}>{children}</body>
    </html>
    </ChatAppProvider>
  )
}
export {metadata};